### ISSUE TITLE
Web View Issue

### ISSUE THREAD

**Issue by Couvel** [mouredev/MyWKWebView#1]
webView = UIWebView()
    webView.frame = CGRect(x:0, y:20, width: self.view.bounds.width, height: self.view.bounds.height-20)

    //after the adjustment, add webView to view panel.
    self.view.addSubview(webView)

    let url = URL(string: "https://wwww.google.com")!
    let request = URLRequest(url: url)

    webView.loadRequest(request)

**Comment by Couvel** [comment]
Solved by myself
i tried loading the same link in a web browser. The initials could change according to your region. Like, it's "https://www.google.co.in/" here. Also try bringing the webView to the front

    self.view.bringSubview(toFront: webView)

**Comment by mouredev** [comment]
Hello, I do not see the correspondence of this code with the one of the project. The project works with WKWebView. 
Could you specify the change ?

Thank you!
